### ISSUE TITLE
read paramter & not changing status of pump

### ISSUE THREAD

**Issue by Axellotel** [fkivela/TurboCtl#1] opened 2022-02-23 10:41 UTC
Hi there,

I'm using your package to communicate with several pumps in our lab. Therefore, I would like to read out the frequency of the pump when the pump is turned on as well as it is turned of. Our problem is that the function "api.read_parameter" causes the status "pump_on" to be True by default. Is there a easy way to read out the parameter and don't change the status? Or do I have to get the status "pump_on" of the pump before and give it over in api.read_parameter?

class TurboVac(object):
    
    def __init__(self, port, baudrate=19200):
        self.connection = serial.Serial(port=port, baudrate=baudrate, timeout=1)
        
    def start_pump(self):
        state = api.status(self.connection, pump_on=True)
        
    def stop_pump(self):
        state = api.status(self.connection, pump_on=False)
        
    def frequency(self):
        freq = api.read_parameter(self.connection, number=3, index=0)[1].parameter_value
        return freq

Thank you in advance

**Comment by fkivela** [comment] 2023-08-03 15:34
Hi!
First, thank you for your interest in TurboCtl! I did not seriously expect it to be used by people outside my group, so it's great to see that it can be of some use to others as well!

Second, sorry for the slow response! I didn't receive any notifications for the issue report and hadn't visited this repo for a long time as I'm not actively developing it anymore.

Third, to you actual question: The issue is that every telegram includes a "pump on/off" bit, which the pump always treats as a "switch pump to this state" instruction, so if one doesn't know the on/off status of the pump, it is impossible to ask it without changing it. If one wants to query e.g. the pump's frequency without affecting the on/off state, then the api.read_parameter function needs to be passed the pump_on argument with the value corresponding to the current state of the pump. This means that the user has to keep track of the on/off status of the pump. So it's not even that you need to first get the "pump_on" status and then give it to read_parameter, because you can't actually even do this, since there's no way to simply read the on/off status of the pump (and this issue is inherent to the pump itself and cannot be affected by TurboCtl). Instead, you need to keep track of the on/off status of the pump yourself and make sure to always pass the correct "pump_on" argument corresponding to the current status of the pump. An alternative solution is to interface with the ui/control_interface module instead of telegram/api. It works a lot like the api, but with a bit more abstraction, and it automatically keeps track of the on/off status of the pump to make sure e.g. reading parameters doesn't change that. The only manual work required is telling it the on/off status of the pump at the moment when the connection to the pump is initialized. The built-in UIs of TurboCtl use ui/control_interface; the initial on/off status is "off" by default and can be set to "on" through a command line argument.

I hope this helps! This explanation is based on my memory and it's been several years since I actively worked on TurboCtl, so let me know if the system doesn't actually seem to work like that, or if you have any further questions.

**Comment by lrlunin** [comment] 2024-03-28 10:42
I have recently contacted the Leybold concerning this question. Their response was:

> Setting bit 10 to 0 does not change the status of the pump.
> However, it should be noted that the start command must still be sent cyclically so that the pump does not shut down automatically unintentionally.

I implemented this approach in my fork and it works! Should I send you a pull request or you would like to implement it by you own? I guess my implementation was a little bit messy in comparison with your awesome and pure codebase (really haven´t seen such clean code before).

UPD: Oups, I pushed this changes to the same branch as my pip packaging pull request was made and you have merged this change as well. Was this intended?

**Comment by fkivela** [comment] 2024-03-28 16:47
Thank you for your interest and contributions (as well as the compliments on my code)! I saw your pull request when you made it several months ago but only now had the time to go through it in detail. I've switched universities since writing TurboCtl and don't have active access to a pump anymore, but today I met with my old supervisor in order to test your changes with his pump.

My tests agree with the comment from Leybold: your updated status function successfully fetches the pump status without changing it, but since it doesn't send the periodical start command, the pump shuts down after 10 seconds. This behaviour seems somewhat obvious in hindsight, but somehow took me until today to figure out. My apologies to Axellotel for my earlier not-entirely-correct answer! (Also, looks like there is no command-line argument to set the initial state of the pump upon starting the program; this must have been something I planned to add but never got around to actually doing.)

I'm planning to build upon your updates by cleaning them up a bit (e.g. adding documentation) and then changing the polling functionality to keep the pump on when it is supposed to stay on. I can handle it myself, but if you have any new code which you think might be useful feel free to make a pull request; even if I end up changing it or cleaning it up, it's usually less work to have a base to build upon. I'm currently doing and testing the changes in the work branch and keeping master untouched so far, so if you make pull requests it's slightly more convenient for me if you make them for work instead of master.

Do you mind if I contact you by email in the (probably near) future for issues relating to the pump? Today's tests with the pump raised some questions for us and it would be great to be able to hear if other users' pumps behave the same way.

I'm reopening the issue since I now know this is something that is possible to fix, and the current version of the program doesn't completely implement the fix yet.

**Comment by fkivela** [comment] 2024-05-22 14:29
I've made some updates to TurboCtl and this issue should now have been fixed. Please let me know if you find any issues in the new version.

**Closed as completed** 2024-05-22 14:30 UTC
